# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 
  pod 'Alamofire', '4.7.1'
  pod 'PopupDialog', '~> 0.6'
pod 'UberRides', '~> 0.9'

  target 'Assignment5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assignment5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
